version: '3'
services:
  # db:
  #   build: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    # ports:
    #   - "3000:3000"
    depends_on:
      - db

  web:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx
    volumes:
      - app
    depends_on:
      - app